apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-app
  labels:
    app.kubernetes.io/name: springboot-demo-app
spec:
  selector:
    app.kubernetes.io/name: springboot-demo-app
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP

